# Project information
site_name: Rho Beta Solutions
site_url: https://rhobeta.io/
site_author: Rho Beta Solutions
site_description: >-
  Explore our knowledge hub and discover valuable insights. Checkout the blog for cool projects.

# # Repository
# repo_name: rhobeta-io/rhobeta.io
# repo_url: https://github.com/rhobeta-io/rhobeta.io

# Copyright
copyright: |
  &copy; 2024 - <a rel="me" href="https://github.com/rhobeta-io">Rho Beta Solutions</a>

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   toggle:
    #     icon: material/toggle-switch-off
    #     name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog:
      enabled: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - obsidian-interactive-graph
  - ezlinks
  - social: # to use social export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
     enabled: !ENV [CI, false]

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rhobeta-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/rhobeta-io
    - icon: material/gmail
      link: mailto:contact@rhobeta.io

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: rhobeta-io
      repo: rhobeta.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js

extra_css:
  - assets/stylesheets/interactive_graph.css

# Page tree
nav:
  - Home: index.md
  - AWS: aws/index.md
  - Kubernetes: kubernetes/index.md
  - Networking:
    - networking/index.md
    - Fundamentals: networking/fundamentals.md
    - Architecture: networking/architectures.md
    - Protocols: networking/protocols.md
    - Security: networking/security.md
    - Management: networking/managment.md
    - Design: networking/design.md
  - CICD: cicd/index.md
  # - About us: about_us.md
  - Blog:
    - blog/index.md
    # - blog/posts/stocks-python.md
    # - blog/posts/data-science.md
    # - blog/posts/github-intro.md
