authors:
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  brascooriol:
    name: Oriol Brasco
    description: Coowner
    avatar: https://github.com/brascooriol.png
    url: https://github.com/brascooriol
  rbrasco:
    name: Roger Brasco
    description: Owner
    avatar: https://github.com/rbrasco.png
    url: https://github.com/rbrasco
  alexvoss:
    name: alexvoss
    description: another
    avatar: https://github.com/rbrasco.png
