authors:
  brascooriol:
    name: Oriol Brasco
    description: Coowner
    avatar: https://github.com/brascooriol.png
    url: https://github.com/brascooriol
  rbrasco:
    name: Roger Brasco
    description: Coowner
    avatar: https://github.com/rbrasco.png
    url: https://github.com/rbrasco
